apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: team14
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: ghcr.io/snuhcs-course/swpp-2026-project-team-14-backend:bootstrap
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz/
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz/
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: team14
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: http
