# Generated by Django 5.2.17 on 2026-09-28 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='garments/')),
                ('original_attributes', models.JSONField()),
                ('attributes', models.JSONField()),
                ('dimensions', models.JSONField(default=None, null=True)),
                ('user_properties', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('saved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
